version: '3.8'
services:
  post-service:
    image: mysql:8.0
    container_name: postservice_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: postservice_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - post_db_data:/var/lib/mysql

volumes:
  post_db_data: